/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:window1:462094:
  appc.background(230);
} //_CODE_:window1:462094:

public void slider2d1_change1(GSlider2D source, GEvent event) { //_CODE_:slider2d1:209508:
  int xMovement = source.getValueXI();
  int yMovement = source.getValueYI();
  
  if (seatStayButtonPressed == true){
    seatstayPivot.x = seatstayPivotOrigX + 0.75*xMovement;
    seatstayPivot.y = seatstayPivotOrigY + 0.75*yMovement;
    seatstayPivot.drawPivot();
  }
  else if (wheelAxleButtonPressed == true){
    wheelAxle.x = wheelAxleOrigX + xMovement;
    wheelAxle.y = wheelAxleOrigY + yMovement;
    wheelAxle.drawPivot();
  }
  
} //_CODE_:slider2d1:209508:

public void startButton_click1(GButton source, GEvent event) { //_CODE_:startButton:653651:
  simulate = true;
  
} //_CODE_:startButton:653651:

public void stopButton_click1(GButton source, GEvent event) { //_CODE_:stopButton:215095:
  simulate = false;
  
} //_CODE_:stopButton:215095:

public void speedSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:speedSlider:986952:
  int a = source.getValueI();
  delay = 75 - (a*25);
  println(delay);
} //_CODE_:speedSlider:986952:

public void seatstayButton_click1(GButton source, GEvent event) { //_CODE_:seatstayButton:568703:
  wheelAxleButtonPressed = false;
  seatStayButtonPressed = true;
  SMUbuttonClicked = false;
} //_CODE_:seatstayButton:568703:

public void SMU_button_click1(GButton source, GEvent event) { //_CODE_:SMUbutton:417080:
  wheelAxleButtonPressed = false;
  seatStayButtonPressed = false;
  SMUbuttonClicked = true;
} //_CODE_:SMUbutton:417080:

public void wheelAxleButton_click1(GButton source, GEvent event) { //_CODE_:wheelAxleButton:327783:
  wheelAxleButtonPressed = true;
  seatStayButtonPressed = false;
  SMUbuttonClicked = false;
} //_CODE_:wheelAxleButton:327783:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 200, 200, 400, 400, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw2");
  slider2d1 = new GSlider2D(window1, 20, 20, 120, 120);
  slider2d1.setLimitsX(0.0, -50.0, 50.0);
  slider2d1.setLimitsY(0.0, -50.0, 50.0);
  slider2d1.setNumberFormat(G4P.INTEGER, 0);
  slider2d1.setOpaque(true);
  slider2d1.addEventHandler(this, "slider2d1_change1");
  startButton = new GButton(window1, 290, 310, 90, 30);
  startButton.setText("Start");
  startButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  startButton.addEventHandler(this, "startButton_click1");
  stopButton = new GButton(window1, 290, 350, 90, 30);
  stopButton.setText("STOP");
  stopButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  stopButton.addEventHandler(this, "stopButton_click1");
  speedSlider = new GCustomSlider(window1, 230, 40, 120, 50, "grey_blue");
  speedSlider.setShowValue(true);
  speedSlider.setShowLimits(true);
  speedSlider.setLimits(1, 1, 3);
  speedSlider.setNbrTicks(3);
  speedSlider.setStickToTicks(true);
  speedSlider.setShowTicks(true);
  speedSlider.setNumberFormat(G4P.INTEGER, 0);
  speedSlider.setOpaque(true);
  speedSlider.addEventHandler(this, "speedSliderChanged");
  label1 = new GLabel(window1, 250, 20, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("SPEED");
  label1.setTextBold();
  label1.setOpaque(false);
  seatstayButton = new GButton(window1, 20, 210, 120, 30);
  seatstayButton.setText("Seatstay");
  seatstayButton.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  seatstayButton.addEventHandler(this, "seatstayButton_click1");
  SMUbutton = new GButton(window1, 20, 250, 120, 30);
  SMUbutton.setText("Shockmount Upper");
  SMUbutton.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  SMUbutton.addEventHandler(this, "SMU_button_click1");
  wheelAxleButton = new GButton(window1, 20, 170, 120, 30);
  wheelAxleButton.setText("Wheel Axle");
  wheelAxleButton.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  wheelAxleButton.addEventHandler(this, "wheelAxleButton_click1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GSlider2D slider2d1; 
GButton startButton; 
GButton stopButton; 
GCustomSlider speedSlider; 
GLabel label1; 
GButton seatstayButton; 
GButton SMUbutton; 
GButton wheelAxleButton; 
